In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('auto.txt')
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# step 2 cleaning the data

# a . drp unwanted columns

In [3]:
df = df.drop('normalized-losses',axis=1)
df.head()

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

# check all columns data types

In [4]:
df.dtypes

symboling              int64
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [5]:
df[['engine-type','num-of-cylinders']]

    engine-type num-of-cylinders
0          dohc             four
1          dohc             four
2          ohcv              six
3           ohc             four
4           ohc             five
..          ...              ...
200         ohc             four
201         ohc             four
202        ohcv              six
203         ohc              six
204         ohc             four

[205 rows x 2 columns]

# c covert object datatype to integer type data type

In [6]:
df['price'] = pd.to_numeric(df['price'],errors='coerce')
df['horsepower'] = pd.to_numeric(df['horsepower'],errors='coerce')
df['peak-rpm'] = pd.to_numeric(df['peak-rpm'],errors='coerce')
df['bore'] = pd.to_numeric(df['bore'],errors='coerce')
df['stroke'] = pd.to_numeric(df['stroke'],errors='coerce')
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

# d convert string to integer

In [7]:
x = df['engine-location'].unique()
eng_loc = {}
for i in range(len(x)):
    eng_loc[x[i]] = i+1
df['engine-location'].replace(eng_loc,inplace=True)
df['engine-location']=pd.to_numeric(df['engine-location'])
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,alfa-romero,gas,std,two,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,alfa-romero,gas,std,two,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,alfa-romero,gas,std,two,hatchback,rwd,1,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,audi,gas,std,four,sedan,fwd,1,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,audi,gas,std,four,sedan,4wd,1,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,volvo,gas,std,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,volvo,gas,turbo,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,volvo,gas,std,four,sedan,rwd,1,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,volvo,diesel,turbo,four,sedan,rwd,1,109.1,188.8,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,volvo,gas,turbo,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [8]:
cylinder = df['num-of-cylinders'].unique()
noc = {}
for i in range(len(cylinder)):
    noc[cylinder[i]] = i+1
df['num-of-cylinders'].replace(noc,inplace=True)
df['num-of-cylinders']=pd.to_numeric(df['num-of-cylinders'])
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,alfa-romero,gas,std,two,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,alfa-romero,gas,std,two,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,alfa-romero,gas,std,two,hatchback,rwd,1,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,audi,gas,std,four,sedan,fwd,1,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,audi,gas,std,four,sedan,4wd,1,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,volvo,gas,std,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,volvo,gas,turbo,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,volvo,gas,std,four,sedan,rwd,1,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,volvo,diesel,turbo,four,sedan,rwd,1,109.1,188.8,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,volvo,gas,turbo,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [9]:
car = df['make'].unique()
make_car = {}
for i in range(len(car)):
    make_car[car[i]] = i+1
df['make'].replace(make_car,inplace=True)
df['make']=pd.to_numeric(df['make'])
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,1,gas,std,two,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,1,gas,std,two,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,1,gas,std,two,hatchback,rwd,1,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,2,gas,std,four,sedan,fwd,1,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,2,gas,std,four,sedan,4wd,1,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,22,gas,std,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,22,gas,turbo,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,22,gas,std,four,sedan,rwd,1,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,22,diesel,turbo,four,sedan,rwd,1,109.1,188.8,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,22,gas,turbo,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [10]:
fuel= df['fuel-type'].unique()
y = {}
for i in range(len(fuel)):
    y[fuel[i]] = i+1
df['fuel-type'].replace(y,inplace=True)
df['fuel-type']=pd.to_numeric(df['fuel-type'])
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,1,1,std,two,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,1,1,std,two,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,1,1,std,two,hatchback,rwd,1,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,2,1,std,four,sedan,fwd,1,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,2,1,std,four,sedan,4wd,1,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,22,1,std,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,22,1,turbo,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,22,1,std,four,sedan,rwd,1,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,22,2,turbo,four,sedan,rwd,1,109.1,188.8,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,22,1,turbo,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [11]:
asp = df['aspiration'].unique()
z = {}
for i in range(len(asp)):
    z[asp[i]] = i+1
df['aspiration'].replace(z,inplace=True)
df['aspiration']=pd.to_numeric(df['aspiration'])
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,1,1,1,two,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,1,1,1,two,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,1,1,1,two,hatchback,rwd,1,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,2,1,1,four,sedan,fwd,1,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,2,1,1,four,sedan,4wd,1,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,22,1,1,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,22,1,2,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,22,1,1,four,sedan,rwd,1,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,22,2,2,four,sedan,rwd,1,109.1,188.8,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,22,1,2,four,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [12]:
doors= df['num-of-doors'].unique()
a = {}
for i in range(len(doors)):
    a[doors[i]] = i+1
df['num-of-doors'].replace(a,inplace=True)
df['num-of-doors']=pd.to_numeric(df['num-of-doors'])
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,1,1,1,1,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,1,1,1,1,convertible,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,1,1,1,1,hatchback,rwd,1,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,2,1,1,2,sedan,fwd,1,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,2,1,1,2,sedan,4wd,1,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,22,1,1,2,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,22,1,2,2,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,22,1,1,2,sedan,rwd,1,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,22,2,2,2,sedan,rwd,1,109.1,188.8,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,22,1,2,2,sedan,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [13]:
body = df['body-style'].unique()
a = {}
for i in range(len(body)):
    a[body[i]] = i+1
df['body-style'].replace(a,inplace=True)
df['body-style']=pd.to_numeric(df['body-style'])
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,1,1,1,1,1,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,1,1,1,1,1,rwd,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,1,1,1,1,2,rwd,1,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,2,1,1,2,3,fwd,1,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,2,1,1,2,3,4wd,1,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,22,1,1,2,3,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,22,1,2,2,3,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,22,1,1,2,3,rwd,1,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,22,2,2,2,3,rwd,1,109.1,188.8,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,22,1,2,2,3,rwd,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [14]:
drive = df['drive-wheels'].unique()
a = {}
for i in range(len(drive)):
    a[drive[i]] = i+1
df['drive-wheels'].replace(a,inplace=True)
df['drive-wheels']=pd.to_numeric(df['drive-wheels'])
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,1,1,1,1,1,1,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,1,1,1,1,1,1,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,1,1,1,1,2,1,1,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,2,1,1,2,3,2,1,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,2,1,1,2,3,3,1,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,22,1,1,2,3,1,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,22,1,2,2,3,1,1,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,22,1,1,2,3,1,1,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,22,2,2,2,3,1,1,109.1,188.8,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,22,1,2,2,3,1,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [15]:
engine = df['engine-type'].unique()
a = {}
for i in range(len(engine)):
    a[engine[i]] = i+1
df['engine-type'].replace(a,inplace=True)
df['engine-type']=pd.to_numeric(df['engine-type'])
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,1,1,1,1,1,1,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,1,1,1,1,1,1,1,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,1,1,1,1,2,1,1,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,2,1,1,2,3,2,1,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,2,1,1,2,3,3,1,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,22,1,1,2,3,1,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,22,1,2,2,3,1,1,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,22,1,1,2,3,1,1,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,22,2,2,2,3,1,1,109.1,188.8,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,22,1,2,2,3,1,1,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [16]:
system = df['fuel-system'].unique()
a = {}
for i in range(len(system)):
    a[system[i]] = i+1
df['fuel-system'].replace(a,inplace=True)
df['fuel-system']=pd.to_numeric(df['fuel-system'])
df

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,1,1,1,1,1,1,1,88.6,168.8,...,130,1,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,1,1,1,1,1,1,1,88.6,168.8,...,130,1,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,1,1,1,1,2,1,1,94.5,171.2,...,152,1,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,2,1,1,2,3,2,1,99.8,176.6,...,109,1,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,2,1,1,2,3,3,1,99.4,176.6,...,136,1,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,22,1,1,2,3,1,1,109.1,188.8,...,141,1,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,22,1,2,2,3,1,1,109.1,188.8,...,141,1,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,22,1,1,2,3,1,1,109.1,188.8,...,173,1,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,22,2,2,2,3,1,1,109.1,188.8,...,145,7,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,22,1,2,2,3,1,1,109.1,188.8,...,141,1,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

# e Check any non values

In [17]:
df.isna().sum()

symboling            0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [23]:
df.columns

Index(['symboling', 'make', 'fuel-type', 'aspiration', 'num-of-doors',
       'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length',
       'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders',
       'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio',
       'city-mpg', 'highway-mpg', 'price'],
      dtype='object')

In [27]:
fill_dict = {'bore':df['bore'].mean(),
             'stroke':df['stroke'].mean(),
            'price':df['price'].mean()}
df.fillna(fill_dict,inplace=True)

# split the data for training

In [28]:
from sklearn.model_selection import train_test_split
x=df.drop('price',axis=1)
y = df['price']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [30]:
df1 = df.drop('price',axis=1)
col = df.columns
for i in col:
    count= len(df.loc[df[i]==0])
    print(f'{i} count is {count}')

symboling count is 67
make count is 0
fuel-type count is 0
aspiration count is 0
num-of-doors count is 0
body-style count is 0
drive-wheels count is 0
engine-location count is 0
wheel-base count is 0
length count is 0
width count is 0
height count is 0
curb-weight count is 0
engine-type count is 0
num-of-cylinders count is 0
engine-size count is 0
fuel-system count is 0
bore count is 0
stroke count is 0
compression-ratio count is 0
city-mpg count is 0
highway-mpg count is 0
price count is 0

In [32]:
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
linear_model.fit(x_train,y_train)

LinearRegression()

In [35]:
linear_predict = linear_model.predict(x_test)

In [36]:
from sklearn.metrics import mean_squared_error
import math
lmodel_mse = mean_squared_error(linear_predict,y_test)
math.sqrt(lmodel_mse)

3893.3387076607237

# train lasso algorithm

In [42]:
from sklearn.linear_model import Lasso

lass_model = Lasso(alpha = 0.5)
lass_model.fit(x_train,y_train)

lasso_predict=lass_model.predict(x_test)
from sklearn.metrics import mean_squared_error

lasso_mse = mean_squared_error(lasso_predict,y_test)
math.sqrt(lasso_mse)

3886.5434015995593

# training ridge algorithm

In [43]:
from sklearn.linear_model import Ridge

rmodel = Ridge()
rmodel.fit(x_train,y_train)

ridge_predict=rmodel.predict(x_test)
from sklearn.metrics import mean_squared_error

ridge_mse = mean_squared_error(ridge_predict,y_test)
math.sqrt(ridge_mse)

3611.476722860725

# conclusion by comparing all algorithem ridge algorithem is giving best performance. so i will prefer ridge algorithem for predicting  the vehical cost